### ISSUE TITLE
Trouble requesting data from the xeno-canto (bird) API

### ISSUE THREAD

**Issue by JasonBernert** [JasonBernert/sound-of-nature#1]
When calling the the xeno-canto API with jQuery's .getJSON() method it returns a XMLHttpRequest error.

**Example:**
`XMLHttpRequest cannot load http://www.xeno-canto.org/api/2/recordings?query=box:45.5,-122.0,46.0,-121.0. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.`

When requesting the data with the JSONP method adding the `callback=?` to the call, there is a syntax error.

**Example**
`Uncaught SyntaxError: Unexpected token :`

I assume the API needs to be called with a different method or I'm not using JSONP correctly.

**Comment by JasonBernert** [comment]
I bugged xeno-canto [on twitter](https://twitter.com/xenocanto/status/791855432591605762) about allowing CORS or JSONP support. [They asked](https://twitter.com/xenocanto/status/791857130018070528) for an example and a comment on the API page. I'll try that...

Maybe just use [JSONProxy](https://jsonp.afeld.me/)?

**Comment by McCambley** [comment]
@JasonBernert Hello from the future, thanks for the tip on using JSONProxy, worked like a charm.

**Comment by Tarrasch** [comment]
Thanks for sharing this on GitHub as this probably reduced my debug time by hours. The JSONProxy idea works, but ideally it shouldn't be necessary right? I tried to follow up [on twitter](https://twitter.com/ArashRouhani/status/1464628027925704710).
